### ISSUE TITLE
New job opening at Jurrasic Park

### ISSUE THREAD

**Issue by yhdesai** [KyleShook/imaginary-opportunities#8]
Hello, Jurassic park has a new job opening, Please add it to the board

Role title: Exotic Animals containment personnel

**Comment by KyleShook** [comment]
@yhdesai I'm afraid there is already a listing for Jurassic Park. It must be a popular place to work! 
[Jurassic Park](https://imaginary-opportunities.vercel.app/listings/frontend/jurassic-park) 
But feel free to add a new listing, if you want. I've included a detailed contribution guide in the Readme.

![image](https://user-images.githubusercontent.com/32422667/207228580-639094b8-88c6-430c-9817-8937568c08bf.png)
